### ISSUE TITLE
Install StyleCop

### ISSUE THREAD

**Issue by J-Mitko** [TeamOfColleages/AnimalMatcher#18]
Use this settings file.
[Settings.StyleCop.txt](https://github.com/TeamOfColleages/AnimalMatcher/files/2468361/Settings.StyleCop.txt)

**Comment by tcholakov** [comment]
StyleCop is installed and configured on all projects all we have to do is build the projects and the issues will pop up as warnings
I advise not to merge in master anything that still has StyleCop warnings
